generatorName: python
templateDir: templates/python
additionalProperties:
  packageName: couchdb_client
  projectName: couchdb-sdk
  packageUrl: https://github.com/laveresteban/couchdb-python
  library: urllib3
  generateSourceCodeOnly: false
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: true
  modelDocs: true
